# Generated by Django 5.2.17 on 2026-10-05 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Optional subject selection within the course and semester.', related_name='enrollments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.subject'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'semester', 'academic_year'), name='unique_student_course_term'),
        ),
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.UniqueConstraint(fields=('name', 'subject'), name='unique_subject_class'),
        ),
    ]
